// Posts
export const POSTS_FETCH_DATA_REJECT = 'POSTS_FETCH_DATA_REJECT';
export const POSTS_FETCH_DATA_REQUEST = 'POSTS_FETCH_DATA_REQUEST';
export const POSTS_FETCH_DATA_SUCCESS = 'POSTS_FETCH_DATA_SUCCESS';
export const POSTS_LOAD_MORE = 'POSTS_LOAD_MORE';
export const POSTS_RESET_LIMIT = 'POSTS_RESET_LIMIT';
export const FIND_POSTS = 'FIND_POSTS';

// Band
export const BAND_FETCH_DATA_REJECT = 'BAND_FETCH_DATA_REJECT';
export const BAND_FETCH_DATA_REQUEST = 'BAND_FETCH_DATA_REQUEST';
export const BAND_FETCH_DATA_SUCCESS = 'BAND_FETCH_DATA_SUCCESS';
export const BAND_SET_VISIBILITY_FILTER = 'BAND_SET_VISIBILITY_FILTER';

//History
export const HISTORY_FETCH_DATA_REJECT = 'HISTORY_FETCH_DATA_REJECT';
export const HISTORY_FETCH_DATA_REQUEST = 'HISTORY_FETCH_DATA_REQUEST';
export const HISTORY_FETCH_DATA_SUCCESS = 'HISTORY_FETCH_DATA_SUCCESS';

// NavBar menu
export const NAVBAR_TOGGLE_MENU = 'NAVBAR_TOGGLE_MENU';

// Slider
export const SLIDER_FETCH_DATA_REJECT = 'SLIDER_FETCH_DATA_REJECT';
export const SLIDER_FETCH_DATA_REQUEST = 'SLIDER_FETCH_DATA_REQUEST';
export const SLIDER_FETCH_DATA_SUCCESS = 'SLIDER_FETCH_DATA_SUCCESS';
export const SLIDER_DOT_CLICK = 'SLIDER_DOT_CLICK';
export const SLIDER_TOGGLE_AUTOPLAY = 'SLIDER_TOGGLE_AUTOPLAY';
export const SLIDER_NEXT_SLIDE = 'SLIDER_NEXT_SLIDE';
export const SLIDER_PREV_SLIDE = 'SLIDER_PREV_SLIDE';
export const SLIDER_TOGGLE_INTERVAL = 'SLIDER_TOGGLE_INTERVAL';

// Music
export const MUSIC_FETCH_DATA_REJECT = 'MUSIC_FETCH_DATA_REJECT';
export const MUSIC_FETCH_DATA_REQUEST = 'MUSIC_FETCH_DATA_REQUEST';
export const MUSIC_FETCH_DATA_SUCCESS = 'MUSIC_FETCH_DATA_SUCCESS';
export const MUSIC_SET_ACTIVE_INDEX = 'MUSIC_SET_ACTIVE_INDEX';
export const FIND_MUSIC = 'FIND_MUSIC';
